// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlnwpotkcudzcusxegyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsbndwb3RrY3VkemN1c3hlZ3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzE5NjUsImV4cCI6MjA3Mzk0Nzk2NX0.XNpSTohD3mRcpqpUGgxCwvhhj5OEOK9UJ6-Pwq_7HD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});